/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "usryboesajljbmeiqtfk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzcnlib2VzYWpsamJtZWlxdGZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5OTgzMDgsImV4cCI6MjA4NjU3NDMwOH0.AhQsBrQkSkux4iYmT8LWDXPMQxKtaPSY-n_0SjSubqY"
